#!/bin/bash
# -*- coding: utf-8 -*-

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null;
done;

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	complete -o default -o nospace -F _git g;
fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add `~/bin` to the `$PATH`
[ -d "${HOME}/bin" ] && PATH="$HOME/bin:$PATH";

# Ruby gems
[ -d "${HOME}/.gem" ] && \
PATH="${HOME}/.gem/ruby/$(ls -1 ${HOME}/.gem/ruby)/bin:${PATH}";

# Local bin
[ -d "${HOME}/.local/bin" ] && PATH="${HOME}/.local/bin:${PATH}";

# Android SDK
[ -d "${HOME}/Android/Sdk" ] && \
[ "${ANDROID_HOME}" != '' ] && \
PATH="${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${PATH}" && \
PATH="${ANDROID_HOME}/tools/bin:${PATH}";

if command -v go 1>/dev/null; then
	export GOPATH="${HOME}/.go";
	[ -d "${GOPATH}/bin" ] && PATH="${GOPATH}/bin:${PATH}";
fi

export NVM_DIR="${HOME}/.nvm";

if [ -d "${NVM_DIR}" ]; then
	# This loads nvm
	[ -s "$NVM_DIR/nvm.sh" ] && . "${NVM_DIR}/nvm.sh"
	# This loads nvm bash_completion
	[ -s "$NVM_DIR/bash_completion" ] && . "${NVM_DIR}/bash_completion"
fi

export PATH;
