#!/bin/sh
#

# Source private, user-local exports
[ -f "${HOME}/.privexports" ] && . "${HOME}/.privexports";

if command -v emacs 2>&1 1>/dev/null; then
	export EDITOR='emacs';
else
	export EDITOR='nano';
fi

if command -v vscodium 2>&1 1>/dev/null; then
	export VISUAL='vscodium';
elif command -v code 2>&1 1>/dev/null; then
	export VISUAL='code';
elif command -v geany 2>&1 1>/dev/null; then
	export VISUAL='geany';
elif command -v gedit 2>&1 1>/dev/null; then
	export VISUAL='gedit';
else
	export VISUAL="${EDITOR}";
fi

export XZ_DEFAULTS='-6eT 0'

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

# devkitPro
if [ -d /opt/devkitpro ]; then
	export DEVKITPRO=/opt/devkitpro;
	export DKP="$DEVKITPRO";
	[ -d "${DEVKITPRO}/devkitARM" ] && \
		export DEVKITARM="${DEVKITPRO}/devkitARM" && \
		export DKA="$DEVKITARM" && \
		PATH="${DEVKITARM}/bin:${PATH}";
	[ -d "${DEVKITPRO}/devkitPPC" ] && \
		export DEVKITPPC="${DEVKITPRO}/devkitPPC" && \
		export DKPPC="$DEVKITPPC" && \
		PATH="${DEVKITPPC}/bin:${PATH}";
	[ -d "${DEVKITPRO}/devkitA64" ] && \
		export DEVKITA64="${DEVKITPRO}/devkitA64" && \
		export DKA64="$DEVKITA64" && \
		PATH="${DEVKITA64}/bin:${PATH}"; \
	[ -d "${DEVKITPRO}/tools" ] && \
		PATH="${DEVKITPRO}/tools/bin:${PATH}";
fi

if test -d /opt/homebrew; then
	PATH="/opt/homebrew/bin:$PATH";
fi

HOMEBREW_NO_ANALYTICS=1;

export HOMEBREW_NO_ANALYTICS;
export PATH;
